POST http://localhost:3000/V5/MastersCustomers/Alter/ColumnsWithPk/{pk}
Content-Type: application/json

{
  "MastersCustomers": "",
  "Mobile": "",
  "DOB": "",
  "GSTNumber": "",
  "City": "",
  "Occupation": "",
  "CompanyName": "",
  "BranchName": ""
}