POST http://localhost:3000/SV4/BranOrdersKKD/Alter/WithPk/{pk}
Content-Type: application/json

{
  "ItemsInOrder": "",
  "CustomerData": "",
  "OrderData": "",
  "AddOnData": "",
  "CheckOutData": ""
}