POST http://localhost:3000/V4/BranOrdersKKD/Insert/SchemaColumnsOnly
Content-Type: application/json

{
  "ItemsInOrder": "",
  "CustomerData": "",
  "OrderData": "",
  "AddOnData": "",
  "CheckOutData": ""
}